# Generated by Django 3.1 on 2020-08-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200829_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='petstore',
            name='latitude',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='petstore',
            name='longitude',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='petstore',
            name='zip_code',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
