# Generated by Django 3.1 on 2020-08-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200830_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='petstore',
            name='neighborhood',
            field=models.CharField(default='', max_length=30),
        ),
    ]
