# Generated by Django 3.1 on 2020-08-30 18:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200830_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='petstore',
            name='species',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=[], size=None),
            preserve_default=False,
        ),
    ]
